journaux_apprentissage/urls.py
"""Defenir des motifs f'URL pour journaux_apprentissage"""
from django.urls import path
from . import views
app_name = 'journaux_apprentissage'
urlpatterns = [
    #Page d'accueil
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #page d'ajout d' un nouveau sujet
    path('new_topic/', views.new_topic, name='new_topic'),
    #page d'ajout d'une nouvelle entree
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

journaux_apprentissage/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """Sujet sur lequel l'utilisateur se documente"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        """Retourne des representations textuelles du models"""
        return  self.text

class Entry(models.Model):
    """une information appris sur le sujet"""
    topic = models.ForeignKey(Topic,on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)


    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """retourne une representation textuelle du sujet"""
        return f"{self.text[:50]}"

journaux_apprentissage/forms.py
from django import forms

from .models import Topic,Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {
            'text': ""
        }
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ""}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


journaux_apprentissage/views.py
from django.shortcuts import render, redirect ,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .forms import TopicForm, EntryForm
from .models import Topic, Entry
def index(request):
    """la page d'accueil pour journal apprentissage"""
    return render(request,'journaux_apprentissage/index.html')
@login_required
def topics(request):
    """Aficher tous les topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'journaux_apprentissage/topics.html',context)
@login_required
def topic(request, topic_id):
    """"Afficher un seul sujet et toutes les entres associes"""
    topic = get_object_or_404(Topic, id=topic_id)
    # Verefier que le sujet appartient au utilisateur courant
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request,'journaux_apprentissage/topic.html',context)
@login_required
def new_topic(request):
    """Ajouter un nouveau sujer"""
    if request.method != "POST":
        #Aucune donnee soumise creer un nouveau sujet
        form = TopicForm()
    else:
        #Donnees POST soumises ,les travailler
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('journaux_apprentissage:topics')
        #Afficher un formulaire vierge ou invalide
    context = {'form':form}
    return render(request,'journaux_apprentissage/new_topic.html',context)
@login_required
def new_entry(request, topic_id):
    """Ajouter un nouvelle entree"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != "POST":
        #aucune entree soumise creer un formulaire vierge
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('journaux_apprentissage:topic', topic_id=topic_id)
    #Afficher le formulaire vierge ou invalide
    context = {'topic':topic, 'form':form}
    return render(request,'journaux_apprentissage/new_entry.html',context)
@login_required
def edit_entry(request, entry_id):
    """modifier une entree existante"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        #Requete initiale , remplir le foumulaire avec l'entree actuelle
        form = EntryForm(instance=entry)
    else:
        #donnees post soumises les traiter
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('journaux_apprentissage:topic', topic_id=topic.id)

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request,'journaux_apprentissage/edit_entry.html',context)

journaux_apprentissage/templates/journaux_apprentissage/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang = "fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <title>Journal d'apprentissage</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'journaux_apprentissage:index' %}">Journal d'apprentissage</a>
<button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation">
    <span class="navbar-toggle-icon"></span></button>
<div class="collapse navbar-collapse" id ="navbarCollapse">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'journaux_apprentissage:topics' %}">Sujets</a>
        </li>
    </ul>
    <ul class="navbar-nav ml auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <span class="navbar-text">Bonjour {{ user.username }}.</span>
        </li>
        <li class="nav-item">
        <form method="post" action="{% url 'utilisateurs:logout' %}" >
            {% csrf_token %}
            <button type="submit" class="btn btn-link" style=" color: gray;">
                Se déconnecter
            </button>
        </form>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'utilisateurs:register' %}">S'inscrire</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'utilisateurs:login' %}">Se connecter</a>
        </li>
        {% endif %}
    </ul>
</div>
</nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    <div>
        {% block content %}{% endblock content %}
    </div>
    </div>
</main>
</body>
</html>

journaux_apprentissage/templates/journaux_apprentissage/edit_entry.html
{% extends 'journaux_apprentissage/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
<h4>
            <a href="{% url 'journaux_apprentissage:topic' topic.id %}"> {{ topic }}</a>
</h4>
{% endblock page_header %}
{% block content %}
    <form method="post" action="{% url 'journaux_apprentissage:edit_entry' entry.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name = "submit" class="btn btn-primary">Enregister les modifications</button>
    {% endbuttons %}
</form>

{% endblock content %}

journaux_apprentissage/templates/journaux_apprentissage/index.html
{% extends "journaux_apprentissage/base.html" %}

{% block page_header %}
    <div class="jumbotron">
    <h1 class="display-4">Suivez vos apprentissage</h1>
<p class="lead">Ce journal sert a enregistrer des notes a propos differentes sujets</p>
    <a class="btn btn-lg btn-primary" href="{% url 'utilisateurs:register' %}"
       role="button">S'inscrire &raquo;</a>
    </div>
{% endblock page_header %}

journaux_apprentissage/templates/journaux_apprentissage/new_entry.html
{% extends 'journaux_apprentissage/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
<h3>
            <a href="{% url 'journaux_apprentissage:topic' topic.id %}">{{ topic }}</a>
</h3>
{% endblock page_header %}
{% block content %}
    <form method="post" action="{% url 'journaux_apprentissage:new_entry' topic.id%}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name = "submit" class="btn btn-primary">Ajouter l'entree</button>
    {% endbuttons %}
</form>

{% endblock content %}

journaux_apprentissage/templates/journaux_apprentissage/new_topic.html
{% extends "journaux_apprentissage/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
            <p>Ajouter un nouveau sujet :</p>
{% endblock page_header %}

{% block content %}

    <form method="post" action="{% url 'journaux_apprentissage:new_topic' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
{% buttons %}
    <button name = "submit" class="btn btn-primary">Ajouter le sujet</button>
    {% endbuttons %}
</form>
{% endblock content %}

journaux_apprentissage/templates/journaux_apprentissage/topic.html
{%extends 'journaux_apprentissage/base.html' %}
{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}
{% block content %}
    <h5>
        <a href = "{% url 'journaux_apprentissage:new_entry' topic.id %}">Ajouter une nouvelle entree</a>
    </h5>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'d F Y, H:i' }}
                <small><a href="{% url 'journaux_apprentissage:edit_entry' entry.id %}">Modifier l'entree</a></small>
            </h4>
           <div class="card-body"> 
                {{ entry.text|linebreaks}}
            </div>
        </div>
        {% empty %}
            <p>Aucun entree n'a ete ajoute a ce sujet</p>
    {% endfor %}
    

{% endblock content %}

journaux_apprentissage/templates/journaux_apprentissage/topics.html
{% extends "journaux_apprentissage/base.html" %}
{% block page_header %}
<h1>Sujets</h1>
{% endblock page_header %}
{% block content %}
    <h5><a href="{% url 'journaux_apprentissage:new_topic'%}">Ajouter un nouveau sujet</a></h5>
<ul>
    {% for topic in topics %}
        <div class="card mb-3">
           <div class="card-body"> 
                <a href="{% url 'journaux_apprentissage:topic' topic.id %}">{{ topic }}</a>
            </div>
        </div>
        {% empty %}
            <p>Aucun sujet n'a encore ete ajoute</p>
    {% endfor %}
</ul>
{% endblock content %}